spring:
  application:
    name: demo-api-a
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: bus-config
      profile: dev
      label: master
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/